language: python

python:
  - 3.6

services: postgresql

env:
  - DJANGO=2.1.7 DB=postgresql

install:
  - pip install -r api/requirements.txt
  - pip install coveralls

before_script:
- psql -c "create user django WITH PASSWORD 'password';" -U postgres
- psql -c "create database drf;" -U postgres
- python api/manage.py test


after_success:
  - coveralls

cache:
  - pip
