#!/usr/env bash
export DOMAIN='localhost:3000'
export SITE_NAME='Questioner'
export SITE_LOGO_URL=''
export SITE_OWNER_NAME='django'
export SITE_OWNER_URL=''
export ADMIN_SITE_HEADER='Questioner Administration'
export API_BROWSER_HEADER='Questioner API'
export DJANGO_USE_X_FORWARDED_HOST=True
export DJANGO_ALLOWED_HOSTS=''
export DJANGO_DEFAULT_PAGE_SIZE=25
export DJANGO_DEFAULT_THROTTLE_RATE_ANON='60/minute'
export DJANGO_DEFAULT_THROTTLE_RATE_USER='120/minute'
export DJANGO_SECRET_KEY='secret key'
export DATABASE_URL='postgres:///drf'
export DATABASE_NAME='drf'
export DATABASE_USER='django'
export DATABASE_PASSWORD='password'
export DATABASE_HOST='localhost'
export DATABASE_CONN_MAX_AGE=60
export EMAIL_SMTP_HOST='localhost'
export EMAIL_SMTP_USER=''
export EMAIL_SMTP_PASSWORD=''
export EMAIL_SMTP_PORT=1025
export DEFAULT_FROM_EMAIL='mail <no-reply@site.me>'
export DEFAULT_SERVER_EMAIL='mail <no-reply@site.me>'
export DJANGO_SENTRY_DSN=''
export DJANGO_SENTRY_LOG_LEVEL=20
