language: python

python:
  - 3.6
addons:
  postgresql: "9.4"
services: postgresql
env:
  - DJANGO=2.1.7 DB=postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=config.settings
  - export PYTHONPATH="/home/travis/build/Ogutu-Brian/questioners"
  - export DJANGO_SECRET_KEY="secret key"
  - export DATABASE_URL='postgres:///drf'
  - export SITE_NAME='Questioner'
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r api/requirements.txt
  - pip install coveralls


before_script:
  - source .travis.sh
  - psql -c "create user django WITH PASSWORD 'password';" -U postgres
  - psql -c "create database drf;" -U postgres

script:
- python api/manage.py makemigrations
- python api/manage.py migrate
- python api/manage.py test users


after_success:
  - coveralls

cache:
  - pip
