language: python

python:
  - 3.6
addons:
  postgresql: "9.4"

services: postgresql

env:
  - DJANGO=2.1.7 DB=postgresql

install:
  - pip install -r requirements.txt
  - pip install coveralls


before_script:
  - psql -c "create user django WITH PASSWORD 'password';" -U postgres
  - psql -c "create database drf;" -U postgres
  - psql -c "ALTER USER django CREATEDB;" -U postgres

script:
- cd api/
- python manage.py makemigrations
- python manage.py migrate
- python manage.py test
- coverage run --source='.' manage.py test
- coverage report 


after_success:
  - coveralls

cache:
  - pip
