# Generated by Django 2.1.7 on 2019-03-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190318_1458'),
        ('questions', '0002_auto_20190313_1103'),
    ]

    operations = [
    ]
