# Generated by Django 2.1.7 on 2019-03-19 00:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questionvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionvote',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 3, 19, 0, 43, 12, 385302, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionvote',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
