# Generated by Django 2.1.7 on 2019-03-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190318_1458'),
        ('questions', '0004_auto_20190319_0453'),
    ]

    operations = [
    ]
