# Generated by Django 2.1.7 on 2019-03-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_merge_20190320_1606'),
        ('questions', '0005_merge_20190320_1506'),
    ]

    operations = [
    ]
