# Generated by Django 2.1.7 on 2019-03-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answervote',
            name='votes',
        ),
    ]
