# Generated by Django 2.1.7 on 2019-03-16 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('scheduled_date', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('image_url', models.ManyToManyField(to='meetups.Image')),
            ],
            options={
                'ordering': ['scheduled_date', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('tag_name',)},
        ),
        migrations.AddField(
            model_name='meetup',
            name='tags',
            field=models.ManyToManyField(to='meetups.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('image_url',)},
        ),
        migrations.AlterUniqueTogether(
            name='meetup',
            unique_together={('body', 'scheduled_date', 'location'), ('title', 'scheduled_date', 'location')},
        ),
    ]
