# Generated by Django 2.1.2 on 2019-03-05 18:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('image_url',)},
        ),
        migrations.AddField(
            model_name='meetup',
            name='image_url',
            field=models.ManyToManyField(to='meetups.Image'),
        ),
    ]
