# Generated by Django 2.1.7 on 2019-03-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_rsvp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsvp',
            old_name='responser',
            new_name='responder',
        ),
    ]
