# Generated by Django 2.1.7 on 2019-03-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_auto_20190312_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='response',
            field=models.CharField(max_length=5),
        ),
    ]
